
stages:          # List of stages for jobs, and their order of execution
  - build

variables:
  DIST_PATH: "/www/workspace/web-blog"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - release
  only:
    - master
  script:
    - cd $DIST_PATH
    - yarn install
    - echo "————————————————Building————————————————"
    - yarn build
    - echo "————————————————Done build——————————————"
    - rm -rf /usr/local/nginx/html/web-blog
    - cp -r /www/workspace/web-blog/docs/.vuepress/dist /usr/local/nginx/html/web-blog