name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

env:
  env_REPO: ${{ vars.REPO }}
  env_OWNER: ${{ vars.OWNER }}
  env_CLIENT_ID: ${{ vars.CLIENT_ID }}
  env_CLIENT_SECRET: ${{ vars.CLIENT_SECRET }}

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    # 并行使用多个node版本
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # 设置node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      # 1、生成静态文件
      - name: Build
        run: |
          echo "$env_REPO"
          export OWNER=$env_OWNER
          export REPO=$env_REPO
          export CLIENT_ID=$env_CLIENT_ID
          export CLIENT_SECRET=$env_.CLIENT_SECRET
          npm install && npm run build

      # 2、部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: FangHaoming/web-blog
          folder: docs/.vuepress/dist/
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
