name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    # 并行使用多个node版本
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # 传输到private
      - name: Transport
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: FangHaoming/web-blog-private
          branch: gh-action
          folder: .
          clean-exlcude: |
            .env
            .github
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
